a=input("Frist Name:")
b=input("Last Name:")
c=input("course name")
c=input("course code:")
c=input("Course lead name:")
d=input("Course Name: ")
e=input("Course Code: ")
f=input("Enrolment Number: ")
