a=input("Frist Name:")
b=input("Last Name:")
c=input("course name")
c=input("course code:")
c=input("Course lead name:")
f=input("How is the course content:")
g=input("We would like to hear if you have any comments/suggestions about the course and class.")
